name = "SmallCollections"
uuid = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
authors = ["matthias314"]
version = "0.1.0"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
StaticVectors = "20fadf95-9e3d-483c-97cd-cab2760e7998"

[weakdeps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"

[extensions]
BangBangExt = "BangBang"

[compat]
BitIntegers = "0.3"
StaticVectors = "1"
BangBang = "0.4"
