name = "SmallCollections"
uuid = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
authors = ["matthias314"]
version = "0.4.1-DEV"

[deps]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"

[weakdeps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extensions]
BangBangExt = "BangBang"
StaticArraysExt = "StaticArrays"

[compat]
julia = "1.10"
BitIntegers = "0.3"
CpuId = "0.3"
BangBang = "0.4"
StaticArrays = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
StructEqualHash = "8bd03d06-bfef-4aaf-8250-1a26cbb401bf"

[targets]
test = ["Test", "BangBang", "StructEqualHash"]
