name = "SmallCollections"
uuid = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
authors = ["matthias314"]
version = "0.1.0"

[deps]
StaticVectors = "20fadf95-9e3d-483c-97cd-cab2760e7998"
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"

[compat]
StaticVectors = "1"
BitIntegers = "0.3"
